name: chronos_care_assignment
description: chronos-care-assignment
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  get_it: ^7.2.0
  auto_route: ^4.0.1
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  retrofit: ^3.0.1+1
  equatable: ^2.0.3
  dio_logger: ^4.0.8+8
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  auto_route_generator: ^4.0.0
  json_serializable: ^6.2.0
  flutter_lints: ^1.0.0
  freezed: ^2.0.3+1
  retrofit_generator: ^4.0.1
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  test: ^1.21.1

flutter:
  uses-material-design: true